-- Client entry point. Rojo turns this folder into a LocalScript named "Client";
-- the UI modules are its children.

local ContentSync = require(script:WaitForChild("ContentSync"))
local SpellsClient = require(script:WaitForChild("SpellsClient"))
local HudUI = require(script:WaitForChild("HudUI"))
local SpellTrackerUI = require(script:WaitForChild("SpellTrackerUI"))
local InventoryUI = require(script:WaitForChild("InventoryUI"))
local BorderFadeUI = require(script:WaitForChild("BorderFadeUI"))
local NotificationUI = require(script:WaitForChild("NotificationUI"))
local PartyUI = require(script:WaitForChild("PartyUI"))
local GuildUI = require(script:WaitForChild("GuildUI"))
local PartyFramesUI = require(script:WaitForChild("PartyFramesUI"))
local PartyMarkerUI = require(script:WaitForChild("PartyMarkerUI"))
local StoreUI = require(script:WaitForChild("StoreUI"))
local QuestUI = require(script:WaitForChild("QuestUI"))
local NpcMenuUI = require(script:WaitForChild("NpcMenuUI"))
local QuestLogUI = require(script:WaitForChild("QuestLogUI"))
local QuestTrackerUI = require(script:WaitForChild("QuestTrackerUI"))
local QuestSfx = require(script:WaitForChild("QuestSfx"))
local QuestMarkerUI = require(script:WaitForChild("QuestMarkerUI"))
local CraftUI = require(script:WaitForChild("CraftUI"))
local SettingsUI = require(script:WaitForChild("SettingsUI"))
local CharacterUI = require(script:WaitForChild("CharacterUI"))
local ShiftLockController = require(script:WaitForChild("ShiftLockController"))
local TargetingController = require(script:WaitForChild("TargetingController"))
local ChatConfig = require(script:WaitForChild("ChatConfig"))
local GatherFeedbackUI = require(script:WaitForChild("GatherFeedbackUI"))
local DamageIndicatorUI = require(script:WaitForChild("DamageIndicatorUI"))
local LevelUpUI = require(script:WaitForChild("LevelUpUI"))
local EnemyLevelUI = require(script:WaitForChild("EnemyLevelUI"))
local EnemyInspectUI = require(script:WaitForChild("EnemyInspectUI"))
local BestiaryUI = require(script:WaitForChild("BestiaryUI"))
local AchievementsUI = require(script:WaitForChild("AchievementsUI"))
local LeaderboardUI = require(script:WaitForChild("LeaderboardUI"))
local PlayerNameplateUI = require(script:WaitForChild("PlayerNameplateUI"))
local PlayerFeedbackSfx = require(script:WaitForChild("PlayerFeedbackSfx"))
local PlayerHurtFeedbackUI = require(script:WaitForChild("PlayerHurtFeedbackUI"))
local CombatSfx = require(script:WaitForChild("CombatSfx"))
local SpellFeedbackSfx = require(script:WaitForChild("SpellFeedbackSfx"))
local AmbientSfx = require(script:WaitForChild("AmbientSfx"))
local DashClient = require(script:WaitForChild("DashClient"))
local CampPlacementUI = require(script:WaitForChild("CampPlacementUI"))
local FurniturePlacementUI = require(script:WaitForChild("FurniturePlacementUI"))
local FurnitureManageUI = require(script:WaitForChild("FurnitureManageUI"))
local CampTimerUI = require(script:WaitForChild("CampTimerUI"))
local ChestUI = require(script:WaitForChild("ChestUI"))
local MarkerUI = require(script:WaitForChild("MarkerUI"))
local ArrowSelectUI = require(script:WaitForChild("ArrowSelectUI"))
local SwingCooldownUI = require(script:WaitForChild("SwingCooldownUI"))

ContentSync.start() -- first: overlays backend item defs onto the mirror
SpellsClient.start() -- seeds/auto-places spell hotbar binds (HudUI renders them)
HudUI.start()
SpellTrackerUI.start() -- TFT-style subclass tracker (right edge, always on)
InventoryUI.start() -- mounts a SECOND tracker instance in its traits column
BorderFadeUI.start()
NotificationUI.start()
PartyUI.start()
GuildUI.start()
PartyFramesUI.start()
PartyMarkerUI.start()
NpcMenuUI.start() -- Hablar/Ver tienda/Ver misiones — opens on NPC ProximityPrompt, before Store/Quest
StoreUI.start()
QuestUI.start() -- quest giver panel (opens via NpcMenuUI, not directly by the ProximityPrompt anymore)
QuestLogUI.start() -- "Quests" tab (J key / top-right button) — all accepted quests, pick which is tracked
QuestTrackerUI.start() -- HUD tracker (top-left, read-only) for the currently tracked quest
QuestSfx.start() -- distinct sound on quest accepted vs completed
QuestMarkerUI.start() -- "!" flotante sobre NPCs con misión disponible/lista para entregar
CraftUI.start() -- crafting panel (V key / top-right button)
SettingsUI.start() -- options menu (gear button, top-right)
CharacterUI.start() -- character sheet (C key / top-right button)
ShiftLockController.start()
TargetingController.start()
ChatConfig.start()
GatherFeedbackUI.start()
DamageIndicatorUI.start()
LevelUpUI.start()
EnemyLevelUI.start()
EnemyInspectUI.start() -- click-to-inspect stat card (any enemy or player, any distance)
BestiaryUI.start() -- "Bestiary" panel (K key / top-right button): kill counts + tiered drop reveal
AchievementsUI.start() -- "Achievements" panel (L key / top-right button): progress bars + gold rewards
LeaderboardUI.start() -- "Leaderboard" panel (T key / top-right button): top players by level/gold/kills
PlayerNameplateUI.start()
PlayerFeedbackSfx.start()
PlayerHurtFeedbackUI.start() -- flash/shake/sonido/rumble al recibir daño
CombatSfx.start()
SpellFeedbackSfx.start() -- sonido de cast/rechazo, ver server/SpellService.lua (SpellFeedback remote)
AmbientSfx.start() -- loop de fondo (pájaros/grillos), crossfade con el ciclo día/noche
DashClient.start() -- executes server-validated innate dashes (Swift Step / Iron Roll)
CampPlacementUI.start()
FurniturePlacementUI.start()
FurnitureManageUI.start()
CampTimerUI.start()
ChestUI.start()
MarkerUI.start() -- click medio: marcar enemigo/loot/piso (solo o para la party con Shift)
ArrowSelectUI.start() -- R key: cycle bow ammo type between owned arrows
SwingCooldownUI.start() -- Minecraft-style bar under the crosshair, same cooldown data as HudUI's hotbar veil