-- Client entry point. Rojo turns this folder into a LocalScript named "Client";
-- the UI modules are its children.

local ContentSync = require(script:WaitForChild("ContentSync"))
local SpellsClient = require(script:WaitForChild("SpellsClient"))
local HudUI = require(script:WaitForChild("HudUI"))
local SpellTrackerUI = require(script:WaitForChild("SpellTrackerUI"))
local InventoryUI = require(script:WaitForChild("InventoryUI"))
local BorderFadeUI = require(script:WaitForChild("BorderFadeUI"))
local NotificationUI = require(script:WaitForChild("NotificationUI"))
local PartyUI = require(script:WaitForChild("PartyUI"))
local PartyFramesUI = require(script:WaitForChild("PartyFramesUI"))
local PartyMarkerUI = require(script:WaitForChild("PartyMarkerUI"))
local StoreUI = require(script:WaitForChild("StoreUI"))
local QuestUI = require(script:WaitForChild("QuestUI"))
local QuestLogUI = require(script:WaitForChild("QuestLogUI"))
local QuestTrackerUI = require(script:WaitForChild("QuestTrackerUI"))
local QuestSfx = require(script:WaitForChild("QuestSfx"))
local CraftUI = require(script:WaitForChild("CraftUI"))
local SettingsUI = require(script:WaitForChild("SettingsUI"))
local CharacterUI = require(script:WaitForChild("CharacterUI"))
local ShiftLockController = require(script:WaitForChild("ShiftLockController"))
local TargetingController = require(script:WaitForChild("TargetingController"))
local ChatConfig = require(script:WaitForChild("ChatConfig"))
local GatherFeedbackUI = require(script:WaitForChild("GatherFeedbackUI"))
local DamageIndicatorUI = require(script:WaitForChild("DamageIndicatorUI"))
local LevelUpUI = require(script:WaitForChild("LevelUpUI"))
local EnemyLevelUI = require(script:WaitForChild("EnemyLevelUI"))
local PlayerNameplateUI = require(script:WaitForChild("PlayerNameplateUI"))
local PlayerFeedbackSfx = require(script:WaitForChild("PlayerFeedbackSfx"))
local CombatSfx = require(script:WaitForChild("CombatSfx"))

ContentSync.start() -- first: overlays backend item defs onto the mirror
SpellsClient.start() -- seeds/auto-places spell hotbar binds (HudUI renders them)
HudUI.start()
SpellTrackerUI.start() -- TFT-style subclass tracker (right edge, always on)
InventoryUI.start() -- mounts a SECOND tracker instance in its traits column
BorderFadeUI.start()
NotificationUI.start()
PartyUI.start()
PartyFramesUI.start()
PartyMarkerUI.start()
StoreUI.start()
QuestUI.start() -- quest giver panel (opens via NPC ProximityPrompt)
QuestLogUI.start() -- "Quests" tab (J key / top-right button) — all accepted quests, pick which is tracked
QuestTrackerUI.start() -- HUD tracker (top-left, read-only) for the currently tracked quest
QuestSfx.start() -- distinct sound on quest accepted vs completed
CraftUI.start() -- crafting panel (V key / top-right button)
SettingsUI.start() -- options menu (gear button, top-right)
CharacterUI.start() -- character sheet (C key / top-right button)
ShiftLockController.start()
TargetingController.start()
ChatConfig.start()
GatherFeedbackUI.start()
DamageIndicatorUI.start()
LevelUpUI.start()
EnemyLevelUI.start()
PlayerNameplateUI.start()
PlayerFeedbackSfx.start()
CombatSfx.start()